In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import ensemble
from sklearn.model_selection import cross_val_score
%matplotlib inline

In [2]:
df = pd.read_csv('C:/Users/vivek/Downloads/LoanStats3d.csv/LoanStats3d.csv',skipinitialspace=True,
    header=1)

C:\Users\vivek\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,24700.0,24700.0,24700.0,36 months,11.99%,820.28,C,C1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,35000.0,35000.0,35000.0,60 months,14.85%,829.90,C,C5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,3600.0,3600.0,3600.0,36 months,13.99%,123.03,C,C4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,10400.0,10400.0,10400.0,60 months,22.45%,289.91,F,F1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,20000.0,20000.0,20000.0,60 months,10.78%,432.66,B,B4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.drop(['id', 'member_id'], 1)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,24700.0,24700.0,24700.0,36 months,11.99%,820.28,C,C1,Engineer,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,35000.0,35000.0,35000.0,60 months,14.85%,829.90,C,C5,Information Systems Officer,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,3600.0,3600.0,3600.0,36 months,13.99%,123.03,C,C4,leadman,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,10400.0,10400.0,10400.0,60 months,22.45%,289.91,F,F1,Contract Specialist,3 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,20000.0,20000.0,20000.0,60 months,10.78%,432.66,B,B4,truck driver,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
5,11950.0,11950.0,11950.0,36 months,13.44%,405.18,C,C3,Veterinary Tecnician,4 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
6,16000.0,16000.0,16000.0,60 months,12.88%,363.07,C,C2,Senior Structural Designer,1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
7,20000.0,20000.0,20000.0,36 months,9.17%,637.58,B,B2,Vice President of Recruiting Operations,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
8,1400.0,1400.0,1400.0,36 months,12.88%,47.10,C,C2,Logistics Manager,3 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
9,18000.0,18000.0,18000.0,60 months,19.48%,471.70,E,E2,Software Manager,7 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
10,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,A2,SERVICE MANAGER,6 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
11,22400.0,22400.0,22400.0,60 months,12.88%,508.30,C,C2,Executive Director,6 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
12,8000.0,8000.0,8000.0,36 months,11.48%,263.74,B,B5,Vendor liaison,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
13,20000.0,20000.0,20000.0,36 months,8.49%,631.26,B,B1,road driver,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
14,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,Senior Manager,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
15,23000.0,23000.0,23000.0,60 months,8.49%,471.77,B,B1,Teacher,5 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
16,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,Program Coordinator,8 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
17,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,tech,8 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
18,29900.0,29900.0,29900.0,60 months,12.88%,678.49,C,C2,Corporate Insurance,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
19,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,Bookkeeper/Accounting,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
20,18000.0,18000.0,18000.0,60 months,11.99%,400.31,C,C1,GS-11,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
21,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,Sales Manager,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
22,28000.0,28000.0,28000.0,36 months,13.44%,949.38,C,C3,Director of Product Development,2 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
23,5000.0,5000.0,5000.0,36 months,13.44%,169.54,C,C3,General Manager,2 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
24,20000.0,20000.0,20000.0,36 months,5.32%,602.30,A,A1,driver,9 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
25,17600.0,17600.0,17600.0,36 months,5.32%,530.03,A,A1,Network Security Specialist III,< 1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
26,16000.0,16000.0,16000.0,60 months,17.97%,406.04,D,D4,Professional Sales Associate,< 1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
27,16000.0,16000.0,16000.0,36 months,12.88%,538.18,C,C2,"Owner, Fee Appraiser",10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
28,15000.0,15000.0,15000.0,36 months,5.32%,451.73,A,A1,DEPUTY SHERIFF,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
29,4225.0,4225.0,4225.0,36 months,14.85%,146.16,C,C5,mechanic,5 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421067,20000.0,20000.0,20000.0,36 months,6.99%,617.46,A,A3,Mission info Tech,2 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421068,4200.0,4200.0,4200.0,36 months,15.99%,147.64,D,D2,supervisor,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421069,26950.0,26950.0,26950.0,36 months,8.19%,846.88,A,A5,NaN,NaN,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421070,23000.0,23000.0,23000.0,60 months,15.59%,554.32,D,D1,Assistant Maint Manager,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421071,18700.0,18700.0,18700.0,60 months,17.86%,473.44,D,D5,Field Supervisor,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421072,6000.0,6000.0,6000.0,36 months,17.86%,216.50,D,D5,Operator,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421073,15000.0,15000.0,15000.0,60 months,11.44%,329.44,B,B4,VP of Operations,4 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421074,25000.0,25000.0,25000.0,60 months,15.99%,607.82,D,D2,Owner,3 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421075,26500.0,26500.0,26500.0,60 months,8.67%,545.87,B,B1,Business Manager,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421076,25000.0,25000.0,25000.0,60 months,15.59%,602.52,D,D1,NaN,NaN,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421077,8000.0,8000.0,8000.0,36 months,8.19%,251.40,A,A5,Sr. Tech,9 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421078,21000.0,21000.0,21000.0,36 months,6.03%,639.15,A,A1,Director,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421079,12000.0,12000.0,12000.0,36 months,9.49%,384.34,B,B2,Bartender,4 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421080,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,A2,Area Director,1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421081,13150.0,13150.0,13150.0,60 months,14.99%,312.77,C,C5,Team Leader,8 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421082,6225.0,6225.0,6225.0,36 months,16.49%,220.37,D,D3,Painter,2 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421083,7000.0,7000.0,7000.0,36 months,14.31%,240.30,C,C4,machining Cell Lead,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421084,10775.0,10775.0,10775.0,36 months,6.03%,327.95,A,A1,Coordinator of RSVP,< 1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421085,4000.0,4000.0,4000.0,36 months,8.67%,126.59,B,B1,Lead Custodian,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421086,7500.0,7500.0,7500.0,36 months,9.49%,240.22,B,B2,Owner,8 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421087,10850.0,10850.0,10850.0,36 months,19.24%,399.04,E,E2,NaN,NaN,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421088,11575.0,11575.0,11575.0,36 months,15.59%,404.61,D,D1,Manager,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421089,12000.0,12000.0,12000.0,36 months,11.99%,398.52,B,B5,KYC Business Analyst,< 1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421090,10000.0,10000.0,10000.0,36 months,11.99%,332.10,B,B5,Office Assistant,8 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421091,24000.0,24000.0,24000.0,36 months,11.99%,797.03,B,B5,Director of Maintenance,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421092,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,D2,Radiologist Technologist,5 years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421093,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,E3,Painter,1 year,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421094,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,B5,Manager Hotel Operations Oasis,10+ years,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(421097, 144)

In [6]:
categorical = df.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
2
term
2
int_rate
111
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
2
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
52
next_pymnt_d
7
last_credit_pull_d
53
application_type
2
verification_status_joint
1
hardship_flag
2
hardship_type
1
hardship_reason
9
hardship_status
3
hardship_start_date
27
hardship_end_date
28
payment_plan_start_date
28
hardship_loan_status
4
debt_settlement_flag
2
debt_settlement_flag_date
45
settlement_status
3
settlement_date
48

In [7]:
df.drop(['url', 'sub_grade', 'emp_title', 'desc', 'zip_code', 'addr_state', 'earliest_cr_line', 'revol_util', 'last_pymnt_d', 'last_credit_pull_d', 'hardship_start_date', 'hardship_end_date', 'debt_settlement_flag_date', 'settlement_date'], 1, inplace=True)

In [8]:
df

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,settlement_status,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,24700.0,24700.0,24700.0,36 months,11.99%,820.28,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
1,NaN,NaN,35000.0,35000.0,35000.0,60 months,14.85%,829.90,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
2,NaN,NaN,3600.0,3600.0,3600.0,36 months,13.99%,123.03,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
3,NaN,NaN,10400.0,10400.0,10400.0,60 months,22.45%,289.91,F,3 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
4,NaN,NaN,20000.0,20000.0,20000.0,60 months,10.78%,432.66,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
5,NaN,NaN,11950.0,11950.0,11950.0,36 months,13.44%,405.18,C,4 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
6,NaN,NaN,16000.0,16000.0,16000.0,60 months,12.88%,363.07,C,1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
7,NaN,NaN,20000.0,20000.0,20000.0,36 months,9.17%,637.58,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
8,NaN,NaN,1400.0,1400.0,1400.0,36 months,12.88%,47.10,C,3 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
9,NaN,NaN,18000.0,18000.0,18000.0,60 months,19.48%,471.70,E,7 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
10,NaN,NaN,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,6 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
11,NaN,NaN,22400.0,22400.0,22400.0,60 months,12.88%,508.30,C,6 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
12,NaN,NaN,8000.0,8000.0,8000.0,36 months,11.48%,263.74,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
13,NaN,NaN,20000.0,20000.0,20000.0,36 months,8.49%,631.26,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
14,NaN,NaN,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
15,NaN,NaN,23000.0,23000.0,23000.0,60 months,8.49%,471.77,B,5 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
16,NaN,NaN,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,8 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
17,NaN,NaN,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,8 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
18,NaN,NaN,29900.0,29900.0,29900.0,60 months,12.88%,678.49,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
19,NaN,NaN,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
20,NaN,NaN,18000.0,18000.0,18000.0,60 months,11.99%,400.31,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
21,NaN,NaN,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
22,NaN,NaN,28000.0,28000.0,28000.0,36 months,13.44%,949.38,C,2 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
23,NaN,NaN,5000.0,5000.0,5000.0,36 months,13.44%,169.54,C,2 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
24,NaN,NaN,20000.0,20000.0,20000.0,36 months,5.32%,602.30,A,9 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
25,NaN,NaN,17600.0,17600.0,17600.0,36 months,5.32%,530.03,A,< 1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
26,NaN,NaN,16000.0,16000.0,16000.0,60 months,17.97%,406.04,D,< 1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
27,NaN,NaN,16000.0,16000.0,16000.0,36 months,12.88%,538.18,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
28,NaN,NaN,15000.0,15000.0,15000.0,36 months,5.32%,451.73,A,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
29,NaN,NaN,4225.0,4225.0,4225.0,36 months,14.85%,146.16,C,5 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421067,NaN,NaN,20000.0,20000.0,20000.0,36 months,6.99%,617.46,A,2 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421068,NaN,NaN,4200.0,4200.0,4200.0,36 months,15.99%,147.64,D,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421069,NaN,NaN,26950.0,26950.0,26950.0,36 months,8.19%,846.88,A,NaN,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421070,NaN,NaN,23000.0,23000.0,23000.0,60 months,15.59%,554.32,D,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421071,NaN,NaN,18700.0,18700.0,18700.0,60 months,17.86%,473.44,D,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421072,NaN,NaN,6000.0,6000.0,6000.0,36 months,17.86%,216.50,D,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421073,NaN,NaN,15000.0,15000.0,15000.0,60 months,11.44%,329.44,B,4 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421074,NaN,NaN,25000.0,25000.0,25000.0,60 months,15.99%,607.82,D,3 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421075,NaN,NaN,26500.0,26500.0,26500.0,60 months,8.67%,545.87,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421076,NaN,NaN,25000.0,25000.0,25000.0,60 months,15.59%,602.52,D,NaN,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421077,NaN,NaN,8000.0,8000.0,8000.0,36 months,8.19%,251.40,A,9 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421078,NaN,NaN,21000.0,21000.0,21000.0,36 months,6.03%,639.15,A,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421079,NaN,NaN,12000.0,12000.0,12000.0,36 months,9.49%,384.34,B,4 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421080,NaN,NaN,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421081,NaN,NaN,13150.0,13150.0,13150.0,60 months,14.99%,312.77,C,8 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421082,NaN,NaN,6225.0,6225.0,6225.0,36 months,16.49%,220.37,D,2 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421083,NaN,NaN,7000.0,7000.0,7000.0,36 months,14.31%,240.30,C,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421084,NaN,NaN,10775.0,10775.0,10775.0,36 months,6.03%,327.95,A,< 1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421085,NaN,NaN,4000.0,4000.0,4000.0,36 months,8.67%,126.59,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421086,NaN,NaN,7500.0,7500.0,7500.0,36 months,9.49%,240.22,B,8 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421087,NaN,NaN,10850.0,10850.0,10850.0,36 months,19.24%,399.04,E,NaN,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421088,NaN,NaN,11575.0,11575.0,11575.0,36 months,15.59%,404.61,D,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421089,NaN,NaN,12000.0,12000.0,12000.0,36 months,11.99%,398.52,B,< 1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421090,NaN,NaN,10000.0,10000.0,10000.0,36 months,11.99%,332.10,B,8 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421091,NaN,NaN,24000.0,24000.0,24000.0,36 months,11.99%,797.03,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421092,NaN,NaN,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,5 years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421093,NaN,NaN,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,1 year,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421094,NaN,NaN,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,10+ years,...,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN
421095,Total amount funded in policy code 1: 6417608175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,Total amount funded in policy code 2: 1944088810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df[['loan_amnt', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'home_ownership', 'annual_inc', 'verification_status', 'loan_status', 'purpose', 'dti', 'open_acc', 'revol_bal', 'total_acc', 'total_pymnt_inv', 'tot_cur_bal', 'total_il_high_credit_limit']]

In [10]:
df = df.dropna()

In [11]:
df.shape

(421093, 18)

In [12]:
categorical = df.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

term
2
int_rate
111
grade
7
home_ownership
4
verification_status
3
loan_status
7
purpose
14

In [13]:
df['int_rate'] = pd.to_numeric(df['int_rate'].str.strip('%'), errors='coerce')

In [14]:
X = df.drop('loan_status', 1)
Y = df['loan_status']
X = pd.get_dummies(X)

rfc = ensemble.RandomForestClassifier(n_estimators=10)

cross_val_score(rfc, X, Y, cv=10)

C:\Users\vivek\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 3 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)

array([0.9137538 , 0.91990216, 0.92253805, 0.91382095, 0.9070767 ,
       0.9053409 , 0.89431937, 0.88553244, 0.87577182, 0.85515128])